repos:
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
      args: ["wagtailsharing", "setup.py", "testmanage.py", "--line-length=79"]
      exclude: migrations
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        exclude: migrations
      - id: ruff-format
        exclude: migrations
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["wagtailsharing"]
